---
name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  couchdb:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20, 22]
        couchdb: ["2.3", "3.3"]
    steps:
      - uses: iamssen/couchdb-github-action@master
        with:
          couchdb-version: ${{ matrix.couchdb }}

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm i -g add-cors-to-couchdb
      - run: add-cors-to-couchdb -u admin -p password

      - run: npm ci

      # install chromium manually
      - run: node node_modules/puppeteer/install.js

      - name: unit test
        run: npm test
        env:
          COUCH_URL: http://admin:password@localhost:5984

      - name: produce coverage report
        run: npm run coveralls
        env:
          COUCH_URL: http://admin:password@localhost:5984

      - name: report coverage to coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
          path-to-lcov: ./lcov.info
  os:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      # install chromium manually
      - run: node node_modules/puppeteer/install.js

      - run: npm test
